/* Generated By:JJTree: Do not edit this line. DocFormalComment.java */

package net.sourceforge.velocidoc.parser;

import java.util.Vector;

public class DocFormalComment extends SimpleNode {
    Vector tags = new Vector();
    Vector params = new Vector();
    String comment;

    public DocFormalComment(int id) {
        super(id);
    }

    public DocFormalComment(MacroParser p, int id) {
        super(p, id);
    }
    public int getTagCount() {
        return tags.size();
    }
    public int getParamCount() {
        return params.size();
    }
    public DocParam getParam(int i) {
        return (DocParam) params.get(i);
    }
    public DocTag getTag(int i) {
        return (DocTag) tags.get(i);
    }
    public void jjtAddChild(Node n, int i) {
        if (n.isA(MacroParserTreeConstants.JJTPARAM)) {
            params.add(0,n);
        } else if (n.isA(MacroParserTreeConstants.JJTTAG)) {
            tags.add( 0,n );
        }
        super.jjtAddChild( n,  i);
    }
    public String getComment() {
        return this.comment;
    }
    public void setComment(String in) {
        this.comment = in;
    }
}

