/* Generated By:JJTree: Do not edit this line. DocMacro.java */

package net.sourceforge.velocidoc.parser;


import java.util.*;

public class DocMacro extends SimpleNode {
    String name;
    String body;
    DocFormalComment docFormalComment;

    Vector arguments = new Vector();

    public void setMacroName(String name) {
        this.name = name;
    }
    public void setMacroBody(String body) {
        this.body = body;
    }
    public int getArgumentCount() {
        return arguments.size();
    }

    public DocMacroArgument getArgument(int i) {
        return (DocMacroArgument) arguments.get(i);
    }
    public DocFormalComment getComment() {
        return this.docFormalComment;
    }
    public Vector getMacroArguments() {
        return (Vector) arguments.clone();
    }
    public String getName() {
        return this.name;
    }
    public String getBody() {
        return this.body;
    }

    public DocMacro(int id) {
        super(id);
    }

    public DocMacro(MacroParser p, int id) {
        super(p, id);
    }

    public void jjtAddChild(Node n, int i) {
        if (n.isA(MacroParserTreeConstants.JJTMACROARGUMENT)) {
            arguments.add(0,n);
        } else if (n.isA(MacroParserTreeConstants.JJTFORMALCOMMENT)) {
            this.docFormalComment = (DocFormalComment) n;
        }
        super.jjtAddChild( n,  i);
    }

}
