/* Generated By:JJTree: Do not edit this line. DocTag.java */

package net.sourceforge.velocidoc.parser;

public class DocMacroUsage extends SimpleNode {
    String macroName;

    public DocMacroUsage(int id) {
        super(id);
    }

    public DocMacroUsage(MacroParser p, int id) {
        super(p, id);
    }
    public String getMacroName() {
        return macroName;
    }
    public void setMacroName(String newMacroName) {
        macroName = newMacroName;
    }

}
