/* Generated By:JJTree: Do not edit this line. DocParam.java */

package net.sourceforge.velocidoc.parser;

public class DocParam extends SimpleNode {
    String name;
    String description;

    public DocParam(int id) {
        super(id);
    }

    public DocParam(MacroParser p, int id) {
        super(p, id);
    }

    public void setDescription(String desc) {
        this.description = desc;
    }
    public void setName(String name) {
        this.name= name;
    }
    public String getName() {
        return name;
    }
    public String getDescription() {
        return description;
    }
}
