/* Generated By:JJTree: Do not edit this line. DocTag.java */

package net.sourceforge.velocidoc.parser;

public class DocTag extends SimpleNode {
    String tagName;
    String value;

    public DocTag(int id) {
        super(id);
    }

    public DocTag(MacroParser p, int id) {
        super(p, id);
    }
    public String getTagName() {
        return tagName;
    }
    public void setTagName(String newTagName) {
        tagName = newTagName.trim();
    }
    public void setValue(String newValue) {
        value = newValue;
    }
    public String getValue() {
        return value;
    }


}
