/* Generated By:JJTree: Do not edit this line. MacroParserTreeConstants.java */

package net.sourceforge.velocidoc.parser;

public interface MacroParserTreeConstants
{
  public int JJTTEMPLATE = 0;
  public int JJTMACRO = 1;
  public int JJTMACROARGUMENT = 2;
  public int JJTVOID = 3;
  public int JJTTAG = 4;
  public int JJTPARAM = 5;
  public int JJTFORMALCOMMENT = 6;
  public int JJTMACROUSAGE = 7;


  public String[] jjtNodeName = {
    "Template",
    "Macro",
    "MacroArgument",
    "void",
    "Tag",
    "Param",
    "FormalComment",
    "MacroUsage",
  };
}
